### ISSUE TITLE
specifying relative path as source for package

### ISSUE THREAD

**Issue by caedn** [pypa/pipfile#50]
I've seen the example for using a git repository as an alternative source:

    pinax = { git = 'git://github.com/pinax/pinax.git', ref = '1.4', editable = true }

What would the `-e .` in requirements.txt equivalent be?

**Comment by dstufft** [comment]
This seems like a reasonable idea.

*Perhaps* it should be restricted so that the relative directory cannot be outside of the tree that contains the ``Pipfile`` (e.g., you cannot use ``..``), however I'm not sure if it really matters, if someone has their system laid out in a specific way, it may not make sense to really worry about trying to enforce something like that.

**Comment by ryneeverett** [comment]
I was thinking the main use case would be specifying directories outside the immediate parent of the Pipfile, but within a version controlled tree. This would be nice for managing dependencies when using the mono-repo pattern and maintaining multiple packages in the same repo, as well as single-project repositories that include an example/testing application directory that depends on the main package.

**Comment by ryanhiebert** [comment]
This is the only blocker that I have for using Pipfile through Pipenv. My deployed application is an installable python package, with my dependencies and a custom entry point declared in `setup.py`. Currently I have a `requirements.in` file (for use with pip-tools) that just has the contents `-e .`. Then the current versions get saved into the `requirements.txt`. I'd much rather use Pipfile, but I need to be able to install my Python package before that'll work.

It would also be acceptable in my case if it was expected that Pipfile would take over all the dependency management, as long as I can find some way to install my package so that I can get my entry point installed.

**Comment by kennethreitz** [comment]
we support "-e ."

I'll add it to the example

**Comment by ryanhiebert** [comment]
@kennethreitz : I'm sorry, I'm really having trouble finding the example you're referring to above, or anything about how `-e .` is supported. I imagine that part of it will be the `{editable=true}`, but I'm not sure how to specify a path. What am I missing?

**Comment by kennethreitz** [comment]
{path=".", editable=True}

**Comment by ryanhiebert** [comment]
Thanks!

**Comment by kennethreitz** [comment]
I need to update the spec.

**Comment by kennethreitz** [comment]
Look at Pipenv for most recent examples.

**Comment by kennethreitz** [comment]
http://docs.pipenv.org/en/latest/

**Comment by kennethreitz** [comment]
Specifically, the advanced section: http://docs.pipenv.org/en/latest/advanced.html#specifying-package-indexes

**Comment by gabrielfalcao** [comment]
updated link: https://pipenv.readthedocs.io/en/latest/advanced/#specifying-package-indexes
